### ISSUE TITLE
support inside a workspace

### ISSUE THREAD

**Issue by jgrund** [neon-bindings/neon#297]
It would be great if neon bindings would work inside a workspace.

Currently it appears you can build, but since the target is at the top level of the workspace, neon can't locate the generated `.so` file.

**Comment by dherman** [comment]
@jgrund Curious, do you mean yarn workspaces or cargo workspaces? I'm guessing yarn?

**Comment by jgrund** [comment]
Cargo workspaces. Here is an example repo where I'm using neon in a workspace: https://github.com/intel-hpdd/rust-libzfs/

**Comment by dherman** [comment]
This is very much top of mind! There's the beginnings of a discussion of using workspaces in the [cargo wrapper RFC](https://github.com/neon-bindings/rfcs/pull/4). I don't think that RFC is 100% nailed yet, but would love your thoughts about it if you have a chance to read it. I will also run through it again and make sure examples like yours are doable.

**Comment by dherman** [comment]
Labeling as `needs RFC` because it should be addressed by the cargo wrapper RFC once it's in a shape we all like (i.e., it doesn't need a separate RFC from that).

**Comment by retep998** [comment]
Just chiming in to say that I would really absolutely love being able to use use neon inside cargo workspaces.

**Comment by kjvalencik** [comment]
@retep998 My use case for workspaces is pretty simple. I wanted to be able to build from the root as well as use RLS in VS Code (which requires the root of the project be a Rust project). If your use case is similar, there is a workaround. Create a `.cargo/config` file that sets the target to `native/target`.

```sh
mkdir -p .cargo
cat >> .cargo/config << EOF
[build]

target-dir = "native/target"
EOF
```

**Comment by dbousamra** [comment]
@kjvalencik This sort of works. It can now find the .so file.

But I receive: `Error: libstd-e39317eb74365d3c.so: cannot open shared object file: No such file or directory`

When i try to require the .node file

**Comment by amilajack** [comment]
Should this be closed now that https://github.com/neon-bindings/neon/pull/442 is resolved?

**Comment by kjvalencik** [comment]
@amilajack I think it should remain open because it still does not support multiple neon modules in a workspace.

**Comment by jhg** [comment]
@kjvalencik limits in support is only about multiple neon modules in a workspace? if the workspace has a neon module, a lib and a cli is it supported currently?

**Comment by kjvalencik** [comment]
@jhg. Yes, that should work perfectly.

**Comment by kjvalencik** [comment]
This was fixed in `neon-cli` and is also not an issue with `cargo-cp-artifact`.
