### ISSUE TITLE
[docs] Electron apps - undefined symbol __cxa_pure_virtual

### ISSUE THREAD

**Issue by mitchhentges** [neon-bindings/neon#394]
Hey, I'm learning how to set up `neon` here, and I'm running into an issue where, upon launching electron, I get the error: `undefined symbol: __cxa_pure_virtual`.

FWIW, I followed the documentation [here](https://neon-bindings.com/docs/electron-apps).
I found #194, but I've interpreted it as the ticket for integrating with `electron-rebuild`, and that the `electron-build-env` process was already functional? :thinking: :smile:

**To reproduce:**
1. `git clone https://github.com/electron/electron-quick-start`
2. `cd electron-quick-start`
3. `npm i neon-hello`
4. `npm i electron-build-env neon-cli --save-dev`
5. `$(npm bin)/neon build neon-hello`
6. Edit `main.js`, adding `require('neon-hello')` to the top
7. `npm start`

```
$ npm start                                         

> electron-quick-start@1.0.0 start /home/mitch/dev/electron-quick-start
> electron .

App threw an error during load
Error: /home/mitch/dev/electron-quick-start/node_modules/neon-hello/native/index.node: undefined symbol: __cxa_pure_virtual
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/mitch/dev/electron-quick-start/node_modules/neon-hello/lib/index.js:1:168)
    at Object.<anonymous> (/home/mitch/dev/electron-quick-start/node_modules/neon-hello/lib/index.js:5:3)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/mitch/dev/electron-quick-start/node_modules/neon-hello/native/index.node: undefined symbol: __cxa_pure_virtual
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/mitch/dev/electron-quick-start/node_modules/neon-hello/lib/index.js:1:168)
    at Object.<anonymous> (/home/mitch/dev/electron-quick-start/node_modules/neon-hello/lib/index.js:5:3)
```

**Comment by amilajack** [comment]
Does the [example](https://github.com/neon-bindings/examples/tree/master/electron-app) work for you?

**Comment by mitchhentges** [comment]
Hmm, I'm able to reproduce the problem in the example, too :thinking: 

![2019-02-03-214548_511x81_scrot](https://user-images.githubusercontent.com/7784737/52192143-10963780-27fd-11e9-9e2d-b4821594fdff.png)

`node --version`: v11.9.0
`npm --version`: 6.7.0

**Comment by Hammster** [comment]
@mitchhentges the versions for the current electron-quickstart should be the follwing, since you use `node 11.9.0` could you try to use `node 10.11.0` when building instead.

|     |     |
| --- | --- |
| Electron | 4.0.4 |
| Node | 10.11.0 |
| Chromium | 69.0.3497.106 |

**Comment by mitchhentges** [comment]
Using `nvm`, I've installed `node@10.11.0`, but I'm still able to reproduce the issue.
I didn't need to install Chromium locally to run `electron-quick-start`.
I did a fresh clone of `electron-quick-start` - looks like they're still on [`electron@4.0.3`](https://github.com/electron/electron-quick-start/blob/master/package-lock.json#L234)

|||
--|--
Electron | 4.0.3
Node | 10.11.0
Chromium | N/A

a|a|a

Hmm :thinking:

**Comment by Hammster** [comment]
@mitchhentges electron comes with a chromium to render the content, no worries. I don't have the time to test the issue currently (currently moving into a new flat) if i find some time at work i will try it though.

**Comment by theJian** [comment]
Related: https://github.com/neon-bindings/examples/pull/30

**Comment by MeryllEssig** [comment]
If someone is interested, I solved the issue by doing what someone did in this post : https://users.rust-lang.org/t/neon-electron-undefined-symbol-cxa-pure-virtual/21223
```
#[no_mangle]
pub extern fn __cxa_pure_virtual() {
    loop{};
}
```
I added this piece of code in my native/src/lib.rs file, rebuilt the project, and it worked for me.

**Comment by amilajack** [comment]
@theJian does neon-bindings/examples#30 resolve this issue?

**Comment by theJian** [comment]
@amilajack It doesn't.
I'm having this issue on Linux machine. The example runs well on mac os though.

**Comment by theJian** [comment]
@mitchhentges It looks like you are using Linux from your screenshot. Have you tested on other platforms?

**Comment by fominok** [comment]
Any updates on this? Cannot run referenced example, but really interested in getting started with electron + neon

**Comment by fominok** [comment]
Well I've tried solution with defining missing fn as suggested by @MeryllEssig  but no it has undefined symbols like _ZN12v88Function3.. and so on

**Comment by stoically** [comment]
@fominok Happened to me when I didn't build with [`electron-build-env`](https://github.com/dherman/electron-build-env) - doing so resolves it for me (in combination with the workaround from @MeryllEssig).

**Comment by kjvalencik** [comment]
Duplicate of https://github.com/neon-bindings/neon/issues/409

**Comment by kjvalencik** [comment]
Re-opening this issue. It is _not_ a duplicate. It's caused by a missing `.cpp(true)` when building `neon-runtime`. It should be fixed in an upcoming PR to resolve several electron issues.

**Comment by fominok** [comment]
@kjvalencik Hello, is this issue fixed? I've just downloaded examples and trying to start electron-app even with neon-cli dependency bumped to 0.3.3 and still receiving this error

**Comment by kjvalencik** [comment]
Yes, it should be fixed. There is an electron test that can be used as an example. The rust neon crate needed to be bumped as well.

https://github.com/neon-bindings/neon/tree/master/test/electron

**Comment by fominok** [comment]
@kjvalencik thank you for the fast reply; I've tried to build this example and have failed with 'lib/cli.js' not found error on `npm i` and different node versions error. I'm new to Node and build steps for this example would be very helpful for me

**Comment by adityapk00** [comment]
Hello. I just tried this on Linux (Ubuntu 18.04), and this still fails with the same error. 

I'm using the latest neon (0.3.3) and `hello-neon` v0.1.1

![image](https://user-images.githubusercontent.com/31996805/71565371-04dde000-2a63-11ea-8a9b-131548129952.png)

**Comment by kjvalencik** [comment]
@adityapk00 That's likely an issue in the examples repo (for example, it's using an older cli version). Can you open an issue there? Thanks!
